export type Embarkation = 'Cherbourg' | 'Queenstown' | 'Southampton';

export interface TitanicPassenger {
  id: string;
  name: string;
  age: number | null;
  sex: 'female' | 'male';
  passengerClass: 1 | 2 | 3;
  fare: number;
  embarked: Embarkation;
  survived: boolean;
  travelGroupSize: number;
  destination: string;
  notes: string;
}

export const titanicPassengers: TitanicPassenger[] = [
  {
    id: 'p-001',
    name: 'Madeleine Astor',
    age: 18,
    sex: 'female',
    passengerClass: 1,
    fare: 151.55,
    embarked: 'Cherbourg',
    survived: true,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'Traveling in a premium first-class cohort with one of the highest fares in the sample.',
  },
  {
    id: 'p-002',
    name: 'John Jacob Astor',
    age: 47,
    sex: 'male',
    passengerClass: 1,
    fare: 151.55,
    embarked: 'Cherbourg',
    survived: false,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'High-fare first-class traveler whose record is useful when comparing class privilege against outcome.',
  },
  {
    id: 'p-003',
    name: 'Margaret Brown',
    age: 44,
    sex: 'female',
    passengerClass: 1,
    fare: 27.72,
    embarked: 'Cherbourg',
    survived: true,
    travelGroupSize: 1,
    destination: 'Denver',
    notes:
      'Solo first-class passenger with a lower fare band than the Astor party, showing intra-class variation.',
  },
  {
    id: 'p-004',
    name: 'Benjamin Guggenheim',
    age: 46,
    sex: 'male',
    passengerClass: 1,
    fare: 51.86,
    embarked: 'Cherbourg',
    survived: false,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'Adds another non-surviving first-class male record to the filtered survival comparison.',
  },
  {
    id: 'p-005',
    name: 'Edith Evans',
    age: 36,
    sex: 'female',
    passengerClass: 1,
    fare: 31,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 1,
    destination: 'London',
    notes:
      'A solo first-class booking from Southampton with a mid-range fare and a positive outcome.',
  },
  {
    id: 'p-006',
    name: 'Thomas Andrews',
    age: 39,
    sex: 'male',
    passengerClass: 1,
    fare: 0,
    embarked: 'Southampton',
    survived: false,
    travelGroupSize: 1,
    destination: 'Belfast',
    notes:
      'Crew-adjacent first-class record with no ticket fare, helpful when spotting outliers in the fare distribution.',
  },
  {
    id: 'p-007',
    name: 'Emma Bucknell',
    age: 60,
    sex: 'female',
    passengerClass: 1,
    fare: 76.29,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 1,
    destination: 'Philadelphia',
    notes:
      'Older first-class passenger whose survival contributes to the age-versus-outcome comparison.',
  },
  {
    id: 'p-008',
    name: 'George Harris',
    age: 62,
    sex: 'male',
    passengerClass: 1,
    fare: 80,
    embarked: 'Southampton',
    survived: false,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'High-fare first-class traveler whose age and outcome stand out in the older cohort.',
  },
  {
    id: 'p-009',
    name: 'Lawrence Beesley',
    age: 34,
    sex: 'male',
    passengerClass: 2,
    fare: 13,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 1,
    destination: 'London',
    notes:
      'Second-class solo passenger with a lower fare profile than first-class travelers and a positive outcome.',
  },
  {
    id: 'p-010',
    name: 'Charlotte Collyer',
    age: 31,
    sex: 'female',
    passengerClass: 2,
    fare: 26,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 2,
    destination: 'Idaho',
    notes:
      'Family traveler whose record helps highlight how grouped bookings behave in second class.',
  },
  {
    id: 'p-011',
    name: 'Harvey Collyer',
    age: 11,
    sex: 'male',
    passengerClass: 2,
    fare: 26,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 2,
    destination: 'Idaho',
    notes:
      'Child passenger useful for the minors KPI and family-size drill-down.',
  },
  {
    id: 'p-012',
    name: 'Kate Buss',
    age: 36,
    sex: 'female',
    passengerClass: 2,
    fare: 21,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 1,
    destination: 'Chicago',
    notes:
      'Another surviving second-class traveler, helping the view show a stronger middle-cabin survival signal.',
  },
  {
    id: 'p-013',
    name: 'Sven Sjostedt',
    age: 28,
    sex: 'male',
    passengerClass: 2,
    fare: 13,
    embarked: 'Southampton',
    survived: false,
    travelGroupSize: 1,
    destination: 'Stockholm',
    notes:
      'Second-class record with a low fare and a negative outcome, adding contrast within the cabin cohort.',
  },
  {
    id: 'p-014',
    name: 'Marion Wright',
    age: 26,
    sex: 'female',
    passengerClass: 2,
    fare: 15.5,
    embarked: 'Cherbourg',
    survived: true,
    travelGroupSize: 1,
    destination: 'New York',
    notes:
      'Young adult second-class passenger embarking at Cherbourg, useful for port-level filtering.',
  },
  {
    id: 'p-015',
    name: 'Samuel Goldenberg',
    age: 49,
    sex: 'male',
    passengerClass: 2,
    fare: 30.07,
    embarked: 'Cherbourg',
    survived: false,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'Higher-fare second-class booking that helps compare family travel versus solo travel within the middle cohort.',
  },
  {
    id: 'p-016',
    name: 'Alice Goldenberg',
    age: 41,
    sex: 'female',
    passengerClass: 2,
    fare: 30.07,
    embarked: 'Cherbourg',
    survived: true,
    travelGroupSize: 2,
    destination: 'New York',
    notes:
      'Paired second-class traveler whose matching fare makes group filtering easier to read in the table.',
  },
  {
    id: 'p-017',
    name: 'Elin Jonsson',
    age: 16,
    sex: 'female',
    passengerClass: 3,
    fare: 7.23,
    embarked: 'Cherbourg',
    survived: true,
    travelGroupSize: 3,
    destination: 'Boston',
    notes:
      'Third-class teenager whose outcome supports age-based exploration in the lower-fare cohort.',
  },
  {
    id: 'p-018',
    name: 'August Lindgren',
    age: 32,
    sex: 'male',
    passengerClass: 3,
    fare: 7.92,
    embarked: 'Southampton',
    survived: false,
    travelGroupSize: 1,
    destination: 'Chicago',
    notes:
      'Solo third-class passenger with a typical low fare and a negative outcome.',
  },
  {
    id: 'p-019',
    name: 'Anna Skoog',
    age: 18,
    sex: 'female',
    passengerClass: 3,
    fare: 16.7,
    embarked: 'Southampton',
    survived: true,
    travelGroupSize: 6,
    destination: 'St. Paul',
    notes:
      'Large-group third-class booking that surfaces clearly when sorting by fare or filtering for young passengers.',
  },
  {
    id: 'p-020',
    name: 'Carl Skoog',
    age: 40,
    sex: 'male',
    passengerClass: 3,
    fare: 16.7,
    embarked: 'Southampton',
    survived: false,
    travelGroupSize: 6,
    destination: 'St. Paul',
    notes:
      'Companion row to the Skoog family entry, useful for comparing mixed outcomes inside the same ticket group.',
  },
  {
    id: 'p-021',
    name: 'Mabel Murdlin',
    age: 9,
    sex: 'female',
    passengerClass: 3,
    fare: 15.25,
    embarked: 'Queenstown',
    survived: true,
    travelGroupSize: 4,
    destination: 'Detroit',
    notes:
      'Young third-class passenger from Queenstown, useful when narrowing the sample by embarkation port.',
  },
  {
    id: 'p-022',
    name: 'William Murdlin',
    age: 40,
    sex: 'male',
    passengerClass: 3,
    fare: 15.25,
    embarked: 'Queenstown',
    survived: false,
    travelGroupSize: 4,
    destination: 'Detroit',
    notes:
      'Third-class family booking from Queenstown, providing a comparable row to Mabel Murdlin.',
  },
  {
    id: 'p-023',
    name: 'Mary Kezia Roberts',
    age: null,
    sex: 'female',
    passengerClass: 3,
    fare: 6.75,
    embarked: 'Queenstown',
    survived: true,
    travelGroupSize: 1,
    destination: 'Montreal',
    notes:
      'Third-class solo traveler with unknown age, helpful for validating how the table handles incomplete fields.',
  },
  {
    id: 'p-024',
    name: 'Patrick Ryan',
    age: null,
    sex: 'male',
    passengerClass: 3,
    fare: 7.75,
    embarked: 'Queenstown',
    survived: false,
    travelGroupSize: 1,
    destination: 'New York',
    notes:
      'Another record with an unknown age, keeping the age-based metrics honest about missing data.',
  },
];
